"""create_initial_schema

Revision ID: 83941aef8ee5
Revises: 
Create Date: 2026-09-18 15:10:16.192998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83941aef8ee5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_queue_id'), ['id'], unique=False)

    op.create_table('memory_procedural',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_statement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_episodic_ids', sa.JSON(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_procedural', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_procedural_id'), ['id'], unique=False)

    op.create_table('memory_semantic',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('statement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_episodic_ids', sa.JSON(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_semantic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_semantic_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('watch_enabled', sa.Boolean(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_project_id'), ['project_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_call_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    op.create_table('memory_episodic',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('consolidated', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_episodic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_episodic_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_episodic_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_episodic_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_episodic_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_episodic_session_id'), ['session_id'], unique=False)

    op.create_table('tool_calls_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('args_json', sa.JSON(), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_calls_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_log_message_id'), ['message_id'], unique=False)

    op.create_table('feedback_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('episodic_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episodic_id'], ['memory_episodic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_events_episodic_id'), ['episodic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_events_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_episodic_id'))

    op.drop_table('feedback_events')
    with op.batch_alter_table('tool_calls_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_log_message_id'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_log_id'))

    op.drop_table('tool_calls_log')
    with op.batch_alter_table('memory_episodic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_episodic_session_id'))
        batch_op.drop_index(batch_op.f('ix_memory_episodic_project_id'))
        batch_op.drop_index(batch_op.f('ix_memory_episodic_message_id'))
        batch_op.drop_index(batch_op.f('ix_memory_episodic_id'))
        batch_op.drop_index(batch_op.f('ix_memory_episodic_created_at'))

    op.drop_table('memory_episodic')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_project_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('memory_semantic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_semantic_id'))

    op.drop_table('memory_semantic')
    with op.batch_alter_table('memory_procedural', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_procedural_id'))

    op.drop_table('memory_procedural')
    with op.batch_alter_table('approval_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_queue_id'))

    op.drop_table('approval_queue')
    # ### end Alembic commands ###
